//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeSimulation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipeSimulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BackView {
            get {
                object obj = ResourceManager.GetObject("BackView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BeginingAnimation {
            get {
                object obj = ResourceManager.GetObject("BeginingAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomView {
            get {
                object obj = ResourceManager.GetObject("BottomView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EndAnimation {
            get {
                object obj = ResourceManager.GetObject("EndAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrontView {
            get {
                object obj = ResourceManager.GetObject("FrontView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the graphics window view in any direction planar to the screen.
        /// </summary>
        internal static string IDS_PAN_DESC {
            get {
                return ResourceManager.GetString("IDS_PAN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamically rotates the view.
        /// </summary>
        internal static string IDS_ROTATE_DESC {
            get {
                return ResourceManager.GetString("IDS_ROTATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamically zooms in or out.
        /// </summary>
        internal static string IDS_ZOOM_DESC {
            get {
                return ResourceManager.GetString("IDS_ZOOM_DESC", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LeftView {
            get {
                object obj = ResourceManager.GetObject("LeftView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarOrbit {
            get {
                object obj = ResourceManager.GetObject("NavBarOrbit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarPan {
            get {
                object obj = ResourceManager.GetObject("NavBarPan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarZoom {
            get {
                object obj = ResourceManager.GetObject("NavBarZoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarZoomAll {
            get {
                object obj = ResourceManager.GetObject("NavBarZoomAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NEIsoMetric {
            get {
                object obj = ResourceManager.GetObject("NEIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NWIsoMetric {
            get {
                object obj = ResourceManager.GetObject("NWIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap record_icon {
            get {
                object obj = ResourceManager.GetObject("record_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightView {
            get {
                object obj = ResourceManager.GetObject("RightView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SEIsoMetric {
            get {
                object obj = ResourceManager.GetObject("SEIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartAnimation {
            get {
                object obj = ResourceManager.GetObject("StartAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopAnimation {
            get {
                object obj = ResourceManager.GetObject("StopAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWIsoMetric {
            get {
                object obj = ResourceManager.GetObject("SWIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SWOrbit {
            get {
                object obj = ResourceManager.GetObject("SWOrbit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SWPan {
            get {
                object obj = ResourceManager.GetObject("SWPan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SWZoom {
            get {
                object obj = ResourceManager.GetObject("SWZoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopView {
            get {
                object obj = ResourceManager.GetObject("TopView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
