# CMake generated Testfile for 
# Source directory: M:/thirdparties/VTK5.6/src/Examples
# Build directory: M:/thirdparties/VTK5.6/src/Examples
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(Build/vtkLocal)
SUBDIRS(Build/vtkMy)
SUBDIRS(AMR/Cxx)
SUBDIRS(Annotation/Cxx/LabeledMesh)
SUBDIRS(MultiBlock/Cxx)
SUBDIRS(GUI/Motif)
SUBDIRS(DataManipulation/Cxx)
SUBDIRS(Hybrid/Cxx)
SUBDIRS(ImageProcessing/Cxx)
SUBDIRS(IO/Cxx)
SUBDIRS(Medical/Cxx)
SUBDIRS(Modelling/Cxx)
SUBDIRS(Rendering/Cxx)
SUBDIRS(Tutorial/Step1/Cxx)
SUBDIRS(Tutorial/Step2/Cxx)
SUBDIRS(Tutorial/Step3/Cxx)
SUBDIRS(Tutorial/Step4/Cxx)
SUBDIRS(Tutorial/Step5/Cxx)
SUBDIRS(Tutorial/Step6/Cxx)
SUBDIRS(VisualizationAlgorithms/Cxx)
SUBDIRS(VolumeRendering/Cxx)
SUBDIRS(Widgets/Cxx)
SUBDIRS(ParallelProcessing)
SUBDIRS(Charts/Cxx)
SUBDIRS(Infovis/Cxx)
SUBDIRS(Array/Cxx)
SUBDIRS(GUI/Win32/SimpleCxx)
SUBDIRS(GUI/Win32/SampleMFC)
SUBDIRS(GUI/Win32/vtkMFC)
