# CMake generated Testfile for 
# Source directory: M:/thirdparties/VTK5.6/src
# Build directory: M:/thirdparties/VTK5.6/src
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(Wrapping)
SUBDIRS(Utilities)
SUBDIRS(Common)
SUBDIRS(Filtering)
SUBDIRS(Imaging)
SUBDIRS(Graphics)
SUBDIRS(GenericFiltering)
SUBDIRS(IO)
SUBDIRS(Rendering)
SUBDIRS(VolumeRendering)
SUBDIRS(Hybrid)
SUBDIRS(Widgets)
SUBDIRS(Parallel)
SUBDIRS(Infovis)
SUBDIRS(Geovis)
SUBDIRS(Views)
SUBDIRS(GUISupport)
SUBDIRS(Charts)
SUBDIRS(Utilities/vtkTclTest2Py)
SUBDIRS(Common/Testing)
SUBDIRS(Filtering/Testing)
SUBDIRS(Graphics/Testing)
SUBDIRS(GenericFiltering/Testing)
SUBDIRS(Imaging/Testing)
SUBDIRS(IO/Testing)
SUBDIRS(Rendering/Testing)
SUBDIRS(VolumeRendering/Testing)
SUBDIRS(Hybrid/Testing)
SUBDIRS(Widgets/Testing)
SUBDIRS(Parallel/Testing)
SUBDIRS(Infovis/Testing)
SUBDIRS(Geovis/Testing)
SUBDIRS(Views/Testing)
SUBDIRS(Charts/Testing)
SUBDIRS(Examples)
SUBDIRS(Utilities/LastConfigureStep)
