#include "vtkGraphicsInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkAppendFilterNew();
extern vtkObject* vtkInstantiatorvtkAppendPolyDataNew();
extern vtkObject* vtkInstantiatorvtkArrayCalculatorNew();
extern vtkObject* vtkInstantiatorvtkArrowSourceNew();
extern vtkObject* vtkInstantiatorvtkAssignAttributeNew();
extern vtkObject* vtkInstantiatorvtkAttributeDataToFieldDataFilterNew();
extern vtkObject* vtkInstantiatorvtkAxesNew();
extern vtkObject* vtkInstantiatorvtkBandedPolyDataContourFilterNew();
extern vtkObject* vtkInstantiatorvtkBlankStructuredGridNew();
extern vtkObject* vtkInstantiatorvtkBlankStructuredGridWithImageNew();
extern vtkObject* vtkInstantiatorvtkBoxClipDataSetNew();
extern vtkObject* vtkInstantiatorvtkBrownianPointsNew();
extern vtkObject* vtkInstantiatorvtkButterflySubdivisionFilterNew();
extern vtkObject* vtkInstantiatorvtkBSPCutsNew();
extern vtkObject* vtkInstantiatorvtkBSPIntersectionsNew();
extern vtkObject* vtkInstantiatorvtkCellCenterDepthSortNew();
extern vtkObject* vtkInstantiatorvtkCellCentersNew();
extern vtkObject* vtkInstantiatorvtkCellDataToPointDataNew();
extern vtkObject* vtkInstantiatorvtkCellDerivativesNew();
extern vtkObject* vtkInstantiatorvtkCleanPolyDataNew();
extern vtkObject* vtkInstantiatorvtkClipDataSetNew();
extern vtkObject* vtkInstantiatorvtkClipPolyDataNew();
extern vtkObject* vtkInstantiatorvtkClipVolumeNew();
extern vtkObject* vtkInstantiatorvtkConeSourceNew();
extern vtkObject* vtkInstantiatorvtkConnectivityFilterNew();
extern vtkObject* vtkInstantiatorvtkContourFilterNew();
extern vtkObject* vtkInstantiatorvtkContourGridNew();
extern vtkObject* vtkInstantiatorvtkCubeSourceNew();
extern vtkObject* vtkInstantiatorvtkCursor3DNew();
extern vtkObject* vtkInstantiatorvtkCutterNew();
extern vtkObject* vtkInstantiatorvtkCurvaturesNew();
extern vtkObject* vtkInstantiatorvtkCylinderSourceNew();
extern vtkObject* vtkInstantiatorvtkDashedStreamLineNew();
extern vtkObject* vtkInstantiatorvtkDataObjectToDataSetFilterNew();
extern vtkObject* vtkInstantiatorvtkDataSetSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkDataSetToDataObjectFilterNew();
extern vtkObject* vtkInstantiatorvtkDataSetTriangleFilterNew();
extern vtkObject* vtkInstantiatorvtkDecimateProNew();
extern vtkObject* vtkInstantiatorvtkDelaunay2DNew();
extern vtkObject* vtkInstantiatorvtkDelaunay3DNew();
extern vtkObject* vtkInstantiatorvtkDiscreteMarchingCubesNew();
extern vtkObject* vtkInstantiatorvtkDiskSourceNew();
extern vtkObject* vtkInstantiatorvtkEdgePointsNew();
extern vtkObject* vtkInstantiatorvtkElevationFilterNew();
extern vtkObject* vtkInstantiatorvtkEllipticalButtonSourceNew();
extern vtkObject* vtkInstantiatorvtkExtractCellsNew();
extern vtkObject* vtkInstantiatorvtkExtractDataOverTimeNew();
extern vtkObject* vtkInstantiatorvtkExtractEdgesNew();
extern vtkObject* vtkInstantiatorvtkExtractGeometryNew();
extern vtkObject* vtkInstantiatorvtkExtractGridNew();
extern vtkObject* vtkInstantiatorvtkExtractPolyDataGeometryNew();
extern vtkObject* vtkInstantiatorvtkExtractRectilinearGridNew();
extern vtkObject* vtkInstantiatorvtkExtractTensorComponentsNew();
extern vtkObject* vtkInstantiatorvtkExtractUnstructuredGridNew();
extern vtkObject* vtkInstantiatorvtkExtractVectorComponentsNew();
extern vtkObject* vtkInstantiatorvtkFeatureEdgesNew();
extern vtkObject* vtkInstantiatorvtkFieldDataToAttributeDataFilterNew();
extern vtkObject* vtkInstantiatorvtkGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkGlyph2DNew();
extern vtkObject* vtkInstantiatorvtkGlyph3DNew();
extern vtkObject* vtkInstantiatorvtkGlyphSource2DNew();
extern vtkObject* vtkInstantiatorvtkGraphLayoutFilterNew();
extern vtkObject* vtkInstantiatorvtkGridSynchronizedTemplates3DNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataSetGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkHedgeHogNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataExtractDataSetsNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataExtractLevelNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataLevelFilterNew();
extern vtkObject* vtkInstantiatorvtkHullNew();
extern vtkObject* vtkInstantiatorvtkHyperStreamlineNew();
extern vtkObject* vtkInstantiatorvtkIdFilterNew();
extern vtkObject* vtkInstantiatorvtkImageDataGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkImageMarchingCubesNew();
extern vtkObject* vtkInstantiatorvtkImplicitTextureCoordsNew();
extern vtkObject* vtkInstantiatorvtkInterpolateDataSetAttributesNew();
extern vtkObject* vtkInstantiatorvtkKdNodeNew();
extern vtkObject* vtkInstantiatorvtkKdTreeNew();
extern vtkObject* vtkInstantiatorvtkLineSourceNew();
extern vtkObject* vtkInstantiatorvtkLinearExtrusionFilterNew();
extern vtkObject* vtkInstantiatorvtkLinearSubdivisionFilterNew();
extern vtkObject* vtkInstantiatorvtkLinkEdgelsNew();
extern vtkObject* vtkInstantiatorvtkLoopSubdivisionFilterNew();
extern vtkObject* vtkInstantiatorvtkMarchingContourFilterNew();
extern vtkObject* vtkInstantiatorvtkMarchingCubesNew();
extern vtkObject* vtkInstantiatorvtkMarchingSquaresNew();
extern vtkObject* vtkInstantiatorvtkMaskFieldsNew();
extern vtkObject* vtkInstantiatorvtkMaskPointsNew();
extern vtkObject* vtkInstantiatorvtkMaskPolyDataNew();
extern vtkObject* vtkInstantiatorvtkMassPropertiesNew();
extern vtkObject* vtkInstantiatorvtkMergeDataObjectFilterNew();
extern vtkObject* vtkInstantiatorvtkMergeCellsNew();
extern vtkObject* vtkInstantiatorvtkMergeFieldsNew();
extern vtkObject* vtkInstantiatorvtkMergeFilterNew();
extern vtkObject* vtkInstantiatorvtkMeshQualityNew();
extern vtkObject* vtkInstantiatorvtkModelMetadataNew();
extern vtkObject* vtkInstantiatorvtkOBBDicerNew();
extern vtkObject* vtkInstantiatorvtkOBBTreeNew();
extern vtkObject* vtkInstantiatorvtkOutlineCornerFilterNew();
extern vtkObject* vtkInstantiatorvtkOutlineCornerSourceNew();
extern vtkObject* vtkInstantiatorvtkOutlineFilterNew();
extern vtkObject* vtkInstantiatorvtkOutlineSourceNew();
extern vtkObject* vtkInstantiatorvtkParametricFunctionSourceNew();
extern vtkObject* vtkInstantiatorvtkPlaneSourceNew();
extern vtkObject* vtkInstantiatorvtkPlanesIntersectionNew();
extern vtkObject* vtkInstantiatorvtkPlatonicSolidSourceNew();
extern vtkObject* vtkInstantiatorvtkPointDataToCellDataNew();
extern vtkObject* vtkInstantiatorvtkPointsProjectedHullNew();
extern vtkObject* vtkInstantiatorvtkPointSourceNew();
extern vtkObject* vtkInstantiatorvtkPolyDataConnectivityFilterNew();
extern vtkObject* vtkInstantiatorvtkPolyDataNormalsNew();
extern vtkObject* vtkInstantiatorvtkPolyDataStreamerNew();
extern vtkObject* vtkInstantiatorvtkProbeFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableAttributeDataFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableDataObjectSourceNew();
extern vtkObject* vtkInstantiatorvtkProgrammableFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableGlyphFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableSourceNew();
extern vtkObject* vtkInstantiatorvtkProjectedTextureNew();
extern vtkObject* vtkInstantiatorvtkQuadricClusteringNew();
extern vtkObject* vtkInstantiatorvtkQuadricDecimationNew();
extern vtkObject* vtkInstantiatorvtkQuantizePolyDataPointsNew();
extern vtkObject* vtkInstantiatorvtkRearrangeFieldsNew();
extern vtkObject* vtkInstantiatorvtkRectangularButtonSourceNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridClipNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridToTetrahedraNew();
extern vtkObject* vtkInstantiatorvtkRectilinearSynchronizedTemplatesNew();
extern vtkObject* vtkInstantiatorvtkRecursiveDividingCubesNew();
extern vtkObject* vtkInstantiatorvtkReflectionFilterNew();
extern vtkObject* vtkInstantiatorvtkRegularPolygonSourceNew();
extern vtkObject* vtkInstantiatorvtkReverseSenseNew();
extern vtkObject* vtkInstantiatorvtkRibbonFilterNew();
extern vtkObject* vtkInstantiatorvtkRotationalExtrusionFilterNew();
extern vtkObject* vtkInstantiatorvtkRotationFilterNew();
extern vtkObject* vtkInstantiatorvtkRuledSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkSelectPolyDataNew();
extern vtkObject* vtkInstantiatorvtkShrinkFilterNew();
extern vtkObject* vtkInstantiatorvtkShrinkPolyDataNew();
extern vtkObject* vtkInstantiatorvtkSimpleElevationFilterNew();
extern vtkObject* vtkInstantiatorvtkSliceCubesNew();
extern vtkObject* vtkInstantiatorvtkSmoothPolyDataFilterNew();
extern vtkObject* vtkInstantiatorvtkSortDataArrayNew();
extern vtkObject* vtkInstantiatorvtkSpatialRepresentationFilterNew();
extern vtkObject* vtkInstantiatorvtkSpherePuzzleNew();
extern vtkObject* vtkInstantiatorvtkSpherePuzzleArrowsNew();
extern vtkObject* vtkInstantiatorvtkSphereSourceNew();
extern vtkObject* vtkInstantiatorvtkSplineFilterNew();
extern vtkObject* vtkInstantiatorvtkSplitFieldNew();
extern vtkObject* vtkInstantiatorvtkStreamLineNew();
extern vtkObject* vtkInstantiatorvtkStreamPointsNew();
extern vtkObject* vtkInstantiatorvtkStreamTracerNew();
extern vtkObject* vtkInstantiatorvtkStripperNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridClipNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridOutlineFilterNew();
extern vtkObject* vtkInstantiatorvtkStructuredPointsGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkSubPixelPositionEdgelsNew();
extern vtkObject* vtkInstantiatorvtkSubdivideTetraNew();
extern vtkObject* vtkInstantiatorvtkSuperquadricSourceNew();
extern vtkObject* vtkInstantiatorvtkSynchronizedTemplates2DNew();
extern vtkObject* vtkInstantiatorvtkSynchronizedTemplates3DNew();
extern vtkObject* vtkInstantiatorvtkSynchronizedTemplatesCutter3DNew();
extern vtkObject* vtkInstantiatorvtkTensorGlyphNew();
extern vtkObject* vtkInstantiatorvtkTextSourceNew();
extern vtkObject* vtkInstantiatorvtkTextureMapToCylinderNew();
extern vtkObject* vtkInstantiatorvtkTextureMapToPlaneNew();
extern vtkObject* vtkInstantiatorvtkTextureMapToSphereNew();
extern vtkObject* vtkInstantiatorvtkTexturedSphereSourceNew();
extern vtkObject* vtkInstantiatorvtkThresholdNew();
extern vtkObject* vtkInstantiatorvtkThresholdPointsNew();
extern vtkObject* vtkInstantiatorvtkThresholdTextureCoordsNew();
extern vtkObject* vtkInstantiatorvtkTransformFilterNew();
extern vtkObject* vtkInstantiatorvtkTransformPolyDataFilterNew();
extern vtkObject* vtkInstantiatorvtkTransformTextureCoordsNew();
extern vtkObject* vtkInstantiatorvtkTriangleFilterNew();
extern vtkObject* vtkInstantiatorvtkTriangularTCoordsNew();
extern vtkObject* vtkInstantiatorvtkTubeFilterNew();
extern vtkObject* vtkInstantiatorvtkVectorDotNew();
extern vtkObject* vtkInstantiatorvtkVectorNormNew();
extern vtkObject* vtkInstantiatorvtkVoxelContoursToSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkWarpLensNew();
extern vtkObject* vtkInstantiatorvtkWarpScalarNew();
extern vtkObject* vtkInstantiatorvtkWarpToNew();
extern vtkObject* vtkInstantiatorvtkWarpVectorNew();
extern vtkObject* vtkInstantiatorvtkWindowedSincPolyDataFilterNew();


  
void vtkGraphicsInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkAppendFilter", vtkInstantiatorvtkAppendFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkAppendPolyData", vtkInstantiatorvtkAppendPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayCalculator", vtkInstantiatorvtkArrayCalculatorNew);
  vtkInstantiator::RegisterInstantiator("vtkArrowSource", vtkInstantiatorvtkArrowSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkAssignAttribute", vtkInstantiatorvtkAssignAttributeNew);
  vtkInstantiator::RegisterInstantiator("vtkAttributeDataToFieldDataFilter", vtkInstantiatorvtkAttributeDataToFieldDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkAxes", vtkInstantiatorvtkAxesNew);
  vtkInstantiator::RegisterInstantiator("vtkBandedPolyDataContourFilter", vtkInstantiatorvtkBandedPolyDataContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkBlankStructuredGrid", vtkInstantiatorvtkBlankStructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkBlankStructuredGridWithImage", vtkInstantiatorvtkBlankStructuredGridWithImageNew);
  vtkInstantiator::RegisterInstantiator("vtkBoxClipDataSet", vtkInstantiatorvtkBoxClipDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkBrownianPoints", vtkInstantiatorvtkBrownianPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkButterflySubdivisionFilter", vtkInstantiatorvtkButterflySubdivisionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkBSPCuts", vtkInstantiatorvtkBSPCutsNew);
  vtkInstantiator::RegisterInstantiator("vtkBSPIntersections", vtkInstantiatorvtkBSPIntersectionsNew);
  vtkInstantiator::RegisterInstantiator("vtkCellCenterDepthSort", vtkInstantiatorvtkCellCenterDepthSortNew);
  vtkInstantiator::RegisterInstantiator("vtkCellCenters", vtkInstantiatorvtkCellCentersNew);
  vtkInstantiator::RegisterInstantiator("vtkCellDataToPointData", vtkInstantiatorvtkCellDataToPointDataNew);
  vtkInstantiator::RegisterInstantiator("vtkCellDerivatives", vtkInstantiatorvtkCellDerivativesNew);
  vtkInstantiator::RegisterInstantiator("vtkCleanPolyData", vtkInstantiatorvtkCleanPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkClipDataSet", vtkInstantiatorvtkClipDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkClipPolyData", vtkInstantiatorvtkClipPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkClipVolume", vtkInstantiatorvtkClipVolumeNew);
  vtkInstantiator::RegisterInstantiator("vtkConeSource", vtkInstantiatorvtkConeSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkConnectivityFilter", vtkInstantiatorvtkConnectivityFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkContourFilter", vtkInstantiatorvtkContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkContourGrid", vtkInstantiatorvtkContourGridNew);
  vtkInstantiator::RegisterInstantiator("vtkCubeSource", vtkInstantiatorvtkCubeSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkCursor3D", vtkInstantiatorvtkCursor3DNew);
  vtkInstantiator::RegisterInstantiator("vtkCutter", vtkInstantiatorvtkCutterNew);
  vtkInstantiator::RegisterInstantiator("vtkCurvatures", vtkInstantiatorvtkCurvaturesNew);
  vtkInstantiator::RegisterInstantiator("vtkCylinderSource", vtkInstantiatorvtkCylinderSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkDashedStreamLine", vtkInstantiatorvtkDashedStreamLineNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectToDataSetFilter", vtkInstantiatorvtkDataObjectToDataSetFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetSurfaceFilter", vtkInstantiatorvtkDataSetSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetToDataObjectFilter", vtkInstantiatorvtkDataSetToDataObjectFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetTriangleFilter", vtkInstantiatorvtkDataSetTriangleFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDecimatePro", vtkInstantiatorvtkDecimateProNew);
  vtkInstantiator::RegisterInstantiator("vtkDelaunay2D", vtkInstantiatorvtkDelaunay2DNew);
  vtkInstantiator::RegisterInstantiator("vtkDelaunay3D", vtkInstantiatorvtkDelaunay3DNew);
  vtkInstantiator::RegisterInstantiator("vtkDiscreteMarchingCubes", vtkInstantiatorvtkDiscreteMarchingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkDiskSource", vtkInstantiatorvtkDiskSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkEdgePoints", vtkInstantiatorvtkEdgePointsNew);
  vtkInstantiator::RegisterInstantiator("vtkElevationFilter", vtkInstantiatorvtkElevationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkEllipticalButtonSource", vtkInstantiatorvtkEllipticalButtonSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractCells", vtkInstantiatorvtkExtractCellsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractDataOverTime", vtkInstantiatorvtkExtractDataOverTimeNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractEdges", vtkInstantiatorvtkExtractEdgesNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractGeometry", vtkInstantiatorvtkExtractGeometryNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractGrid", vtkInstantiatorvtkExtractGridNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractPolyDataGeometry", vtkInstantiatorvtkExtractPolyDataGeometryNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractRectilinearGrid", vtkInstantiatorvtkExtractRectilinearGridNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractTensorComponents", vtkInstantiatorvtkExtractTensorComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractUnstructuredGrid", vtkInstantiatorvtkExtractUnstructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractVectorComponents", vtkInstantiatorvtkExtractVectorComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkFeatureEdges", vtkInstantiatorvtkFeatureEdgesNew);
  vtkInstantiator::RegisterInstantiator("vtkFieldDataToAttributeDataFilter", vtkInstantiatorvtkFieldDataToAttributeDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkGeometryFilter", vtkInstantiatorvtkGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkGlyph2D", vtkInstantiatorvtkGlyph2DNew);
  vtkInstantiator::RegisterInstantiator("vtkGlyph3D", vtkInstantiatorvtkGlyph3DNew);
  vtkInstantiator::RegisterInstantiator("vtkGlyphSource2D", vtkInstantiatorvtkGlyphSource2DNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphLayoutFilter", vtkInstantiatorvtkGraphLayoutFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkGridSynchronizedTemplates3D", vtkInstantiatorvtkGridSynchronizedTemplates3DNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataSetGeometryFilter", vtkInstantiatorvtkHierarchicalDataSetGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHedgeHog", vtkInstantiatorvtkHedgeHogNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataExtractDataSets", vtkInstantiatorvtkHierarchicalDataExtractDataSetsNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataExtractLevel", vtkInstantiatorvtkHierarchicalDataExtractLevelNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataLevelFilter", vtkInstantiatorvtkHierarchicalDataLevelFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHull", vtkInstantiatorvtkHullNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperStreamline", vtkInstantiatorvtkHyperStreamlineNew);
  vtkInstantiator::RegisterInstantiator("vtkIdFilter", vtkInstantiatorvtkIdFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDataGeometryFilter", vtkInstantiatorvtkImageDataGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMarchingCubes", vtkInstantiatorvtkImageMarchingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitTextureCoords", vtkInstantiatorvtkImplicitTextureCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkInterpolateDataSetAttributes", vtkInstantiatorvtkInterpolateDataSetAttributesNew);
  vtkInstantiator::RegisterInstantiator("vtkKdNode", vtkInstantiatorvtkKdNodeNew);
  vtkInstantiator::RegisterInstantiator("vtkKdTree", vtkInstantiatorvtkKdTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkLineSource", vtkInstantiatorvtkLineSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkLinearExtrusionFilter", vtkInstantiatorvtkLinearExtrusionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkLinearSubdivisionFilter", vtkInstantiatorvtkLinearSubdivisionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkLinkEdgels", vtkInstantiatorvtkLinkEdgelsNew);
  vtkInstantiator::RegisterInstantiator("vtkLoopSubdivisionFilter", vtkInstantiatorvtkLoopSubdivisionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMarchingContourFilter", vtkInstantiatorvtkMarchingContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMarchingCubes", vtkInstantiatorvtkMarchingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkMarchingSquares", vtkInstantiatorvtkMarchingSquaresNew);
  vtkInstantiator::RegisterInstantiator("vtkMaskFields", vtkInstantiatorvtkMaskFieldsNew);
  vtkInstantiator::RegisterInstantiator("vtkMaskPoints", vtkInstantiatorvtkMaskPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkMaskPolyData", vtkInstantiatorvtkMaskPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkMassProperties", vtkInstantiatorvtkMassPropertiesNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeDataObjectFilter", vtkInstantiatorvtkMergeDataObjectFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeCells", vtkInstantiatorvtkMergeCellsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeFields", vtkInstantiatorvtkMergeFieldsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeFilter", vtkInstantiatorvtkMergeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMeshQuality", vtkInstantiatorvtkMeshQualityNew);
  vtkInstantiator::RegisterInstantiator("vtkModelMetadata", vtkInstantiatorvtkModelMetadataNew);
  vtkInstantiator::RegisterInstantiator("vtkOBBDicer", vtkInstantiatorvtkOBBDicerNew);
  vtkInstantiator::RegisterInstantiator("vtkOBBTree", vtkInstantiatorvtkOBBTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineCornerFilter", vtkInstantiatorvtkOutlineCornerFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineCornerSource", vtkInstantiatorvtkOutlineCornerSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineFilter", vtkInstantiatorvtkOutlineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineSource", vtkInstantiatorvtkOutlineSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricFunctionSource", vtkInstantiatorvtkParametricFunctionSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPlaneSource", vtkInstantiatorvtkPlaneSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPlanesIntersection", vtkInstantiatorvtkPlanesIntersectionNew);
  vtkInstantiator::RegisterInstantiator("vtkPlatonicSolidSource", vtkInstantiatorvtkPlatonicSolidSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPointDataToCellData", vtkInstantiatorvtkPointDataToCellDataNew);
  vtkInstantiator::RegisterInstantiator("vtkPointsProjectedHull", vtkInstantiatorvtkPointsProjectedHullNew);
  vtkInstantiator::RegisterInstantiator("vtkPointSource", vtkInstantiatorvtkPointSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataConnectivityFilter", vtkInstantiatorvtkPolyDataConnectivityFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataNormals", vtkInstantiatorvtkPolyDataNormalsNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataStreamer", vtkInstantiatorvtkPolyDataStreamerNew);
  vtkInstantiator::RegisterInstantiator("vtkProbeFilter", vtkInstantiatorvtkProbeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableAttributeDataFilter", vtkInstantiatorvtkProgrammableAttributeDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableDataObjectSource", vtkInstantiatorvtkProgrammableDataObjectSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableFilter", vtkInstantiatorvtkProgrammableFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableGlyphFilter", vtkInstantiatorvtkProgrammableGlyphFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableSource", vtkInstantiatorvtkProgrammableSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkProjectedTexture", vtkInstantiatorvtkProjectedTextureNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadricClustering", vtkInstantiatorvtkQuadricClusteringNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadricDecimation", vtkInstantiatorvtkQuadricDecimationNew);
  vtkInstantiator::RegisterInstantiator("vtkQuantizePolyDataPoints", vtkInstantiatorvtkQuantizePolyDataPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkRearrangeFields", vtkInstantiatorvtkRearrangeFieldsNew);
  vtkInstantiator::RegisterInstantiator("vtkRectangularButtonSource", vtkInstantiatorvtkRectangularButtonSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridClip", vtkInstantiatorvtkRectilinearGridClipNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridGeometryFilter", vtkInstantiatorvtkRectilinearGridGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridToTetrahedra", vtkInstantiatorvtkRectilinearGridToTetrahedraNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearSynchronizedTemplates", vtkInstantiatorvtkRectilinearSynchronizedTemplatesNew);
  vtkInstantiator::RegisterInstantiator("vtkRecursiveDividingCubes", vtkInstantiatorvtkRecursiveDividingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkReflectionFilter", vtkInstantiatorvtkReflectionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRegularPolygonSource", vtkInstantiatorvtkRegularPolygonSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkReverseSense", vtkInstantiatorvtkReverseSenseNew);
  vtkInstantiator::RegisterInstantiator("vtkRibbonFilter", vtkInstantiatorvtkRibbonFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRotationalExtrusionFilter", vtkInstantiatorvtkRotationalExtrusionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRotationFilter", vtkInstantiatorvtkRotationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRuledSurfaceFilter", vtkInstantiatorvtkRuledSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSelectPolyData", vtkInstantiatorvtkSelectPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkShrinkFilter", vtkInstantiatorvtkShrinkFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkShrinkPolyData", vtkInstantiatorvtkShrinkPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkSimpleElevationFilter", vtkInstantiatorvtkSimpleElevationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSliceCubes", vtkInstantiatorvtkSliceCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkSmoothPolyDataFilter", vtkInstantiatorvtkSmoothPolyDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSortDataArray", vtkInstantiatorvtkSortDataArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkSpatialRepresentationFilter", vtkInstantiatorvtkSpatialRepresentationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSpherePuzzle", vtkInstantiatorvtkSpherePuzzleNew);
  vtkInstantiator::RegisterInstantiator("vtkSpherePuzzleArrows", vtkInstantiatorvtkSpherePuzzleArrowsNew);
  vtkInstantiator::RegisterInstantiator("vtkSphereSource", vtkInstantiatorvtkSphereSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSplineFilter", vtkInstantiatorvtkSplineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSplitField", vtkInstantiatorvtkSplitFieldNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamLine", vtkInstantiatorvtkStreamLineNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamPoints", vtkInstantiatorvtkStreamPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamTracer", vtkInstantiatorvtkStreamTracerNew);
  vtkInstantiator::RegisterInstantiator("vtkStripper", vtkInstantiatorvtkStripperNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridClip", vtkInstantiatorvtkStructuredGridClipNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridGeometryFilter", vtkInstantiatorvtkStructuredGridGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridOutlineFilter", vtkInstantiatorvtkStructuredGridOutlineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredPointsGeometryFilter", vtkInstantiatorvtkStructuredPointsGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSubPixelPositionEdgels", vtkInstantiatorvtkSubPixelPositionEdgelsNew);
  vtkInstantiator::RegisterInstantiator("vtkSubdivideTetra", vtkInstantiatorvtkSubdivideTetraNew);
  vtkInstantiator::RegisterInstantiator("vtkSuperquadricSource", vtkInstantiatorvtkSuperquadricSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSynchronizedTemplates2D", vtkInstantiatorvtkSynchronizedTemplates2DNew);
  vtkInstantiator::RegisterInstantiator("vtkSynchronizedTemplates3D", vtkInstantiatorvtkSynchronizedTemplates3DNew);
  vtkInstantiator::RegisterInstantiator("vtkSynchronizedTemplatesCutter3D", vtkInstantiatorvtkSynchronizedTemplatesCutter3DNew);
  vtkInstantiator::RegisterInstantiator("vtkTensorGlyph", vtkInstantiatorvtkTensorGlyphNew);
  vtkInstantiator::RegisterInstantiator("vtkTextSource", vtkInstantiatorvtkTextSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkTextureMapToCylinder", vtkInstantiatorvtkTextureMapToCylinderNew);
  vtkInstantiator::RegisterInstantiator("vtkTextureMapToPlane", vtkInstantiatorvtkTextureMapToPlaneNew);
  vtkInstantiator::RegisterInstantiator("vtkTextureMapToSphere", vtkInstantiatorvtkTextureMapToSphereNew);
  vtkInstantiator::RegisterInstantiator("vtkTexturedSphereSource", vtkInstantiatorvtkTexturedSphereSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkThreshold", vtkInstantiatorvtkThresholdNew);
  vtkInstantiator::RegisterInstantiator("vtkThresholdPoints", vtkInstantiatorvtkThresholdPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkThresholdTextureCoords", vtkInstantiatorvtkThresholdTextureCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformFilter", vtkInstantiatorvtkTransformFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformPolyDataFilter", vtkInstantiatorvtkTransformPolyDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformTextureCoords", vtkInstantiatorvtkTransformTextureCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangleFilter", vtkInstantiatorvtkTriangleFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangularTCoords", vtkInstantiatorvtkTriangularTCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkTubeFilter", vtkInstantiatorvtkTubeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkVectorDot", vtkInstantiatorvtkVectorDotNew);
  vtkInstantiator::RegisterInstantiator("vtkVectorNorm", vtkInstantiatorvtkVectorNormNew);
  vtkInstantiator::RegisterInstantiator("vtkVoxelContoursToSurfaceFilter", vtkInstantiatorvtkVoxelContoursToSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpLens", vtkInstantiatorvtkWarpLensNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpScalar", vtkInstantiatorvtkWarpScalarNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpTo", vtkInstantiatorvtkWarpToNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpVector", vtkInstantiatorvtkWarpVectorNew);
  vtkInstantiator::RegisterInstantiator("vtkWindowedSincPolyDataFilter", vtkInstantiatorvtkWindowedSincPolyDataFilterNew);

  
}
          
void vtkGraphicsInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkAppendFilter", vtkInstantiatorvtkAppendFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAppendPolyData", vtkInstantiatorvtkAppendPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayCalculator", vtkInstantiatorvtkArrayCalculatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrowSource", vtkInstantiatorvtkArrowSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssignAttribute", vtkInstantiatorvtkAssignAttributeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAttributeDataToFieldDataFilter", vtkInstantiatorvtkAttributeDataToFieldDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAxes", vtkInstantiatorvtkAxesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBandedPolyDataContourFilter", vtkInstantiatorvtkBandedPolyDataContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBlankStructuredGrid", vtkInstantiatorvtkBlankStructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBlankStructuredGridWithImage", vtkInstantiatorvtkBlankStructuredGridWithImageNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBoxClipDataSet", vtkInstantiatorvtkBoxClipDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBrownianPoints", vtkInstantiatorvtkBrownianPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkButterflySubdivisionFilter", vtkInstantiatorvtkButterflySubdivisionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBSPCuts", vtkInstantiatorvtkBSPCutsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBSPIntersections", vtkInstantiatorvtkBSPIntersectionsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellCenterDepthSort", vtkInstantiatorvtkCellCenterDepthSortNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellCenters", vtkInstantiatorvtkCellCentersNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellDataToPointData", vtkInstantiatorvtkCellDataToPointDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellDerivatives", vtkInstantiatorvtkCellDerivativesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCleanPolyData", vtkInstantiatorvtkCleanPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipDataSet", vtkInstantiatorvtkClipDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipPolyData", vtkInstantiatorvtkClipPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipVolume", vtkInstantiatorvtkClipVolumeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConeSource", vtkInstantiatorvtkConeSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConnectivityFilter", vtkInstantiatorvtkConnectivityFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkContourFilter", vtkInstantiatorvtkContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkContourGrid", vtkInstantiatorvtkContourGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCubeSource", vtkInstantiatorvtkCubeSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCursor3D", vtkInstantiatorvtkCursor3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCutter", vtkInstantiatorvtkCutterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCurvatures", vtkInstantiatorvtkCurvaturesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCylinderSource", vtkInstantiatorvtkCylinderSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDashedStreamLine", vtkInstantiatorvtkDashedStreamLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectToDataSetFilter", vtkInstantiatorvtkDataObjectToDataSetFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetSurfaceFilter", vtkInstantiatorvtkDataSetSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetToDataObjectFilter", vtkInstantiatorvtkDataSetToDataObjectFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetTriangleFilter", vtkInstantiatorvtkDataSetTriangleFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDecimatePro", vtkInstantiatorvtkDecimateProNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDelaunay2D", vtkInstantiatorvtkDelaunay2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDelaunay3D", vtkInstantiatorvtkDelaunay3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDiscreteMarchingCubes", vtkInstantiatorvtkDiscreteMarchingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDiskSource", vtkInstantiatorvtkDiskSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEdgePoints", vtkInstantiatorvtkEdgePointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkElevationFilter", vtkInstantiatorvtkElevationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEllipticalButtonSource", vtkInstantiatorvtkEllipticalButtonSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractCells", vtkInstantiatorvtkExtractCellsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractDataOverTime", vtkInstantiatorvtkExtractDataOverTimeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractEdges", vtkInstantiatorvtkExtractEdgesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractGeometry", vtkInstantiatorvtkExtractGeometryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractGrid", vtkInstantiatorvtkExtractGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractPolyDataGeometry", vtkInstantiatorvtkExtractPolyDataGeometryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractRectilinearGrid", vtkInstantiatorvtkExtractRectilinearGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractTensorComponents", vtkInstantiatorvtkExtractTensorComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractUnstructuredGrid", vtkInstantiatorvtkExtractUnstructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractVectorComponents", vtkInstantiatorvtkExtractVectorComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFeatureEdges", vtkInstantiatorvtkFeatureEdgesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFieldDataToAttributeDataFilter", vtkInstantiatorvtkFieldDataToAttributeDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGeometryFilter", vtkInstantiatorvtkGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlyph2D", vtkInstantiatorvtkGlyph2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlyph3D", vtkInstantiatorvtkGlyph3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlyphSource2D", vtkInstantiatorvtkGlyphSource2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphLayoutFilter", vtkInstantiatorvtkGraphLayoutFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGridSynchronizedTemplates3D", vtkInstantiatorvtkGridSynchronizedTemplates3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataSetGeometryFilter", vtkInstantiatorvtkHierarchicalDataSetGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHedgeHog", vtkInstantiatorvtkHedgeHogNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataExtractDataSets", vtkInstantiatorvtkHierarchicalDataExtractDataSetsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataExtractLevel", vtkInstantiatorvtkHierarchicalDataExtractLevelNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataLevelFilter", vtkInstantiatorvtkHierarchicalDataLevelFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHull", vtkInstantiatorvtkHullNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperStreamline", vtkInstantiatorvtkHyperStreamlineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIdFilter", vtkInstantiatorvtkIdFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDataGeometryFilter", vtkInstantiatorvtkImageDataGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMarchingCubes", vtkInstantiatorvtkImageMarchingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitTextureCoords", vtkInstantiatorvtkImplicitTextureCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInterpolateDataSetAttributes", vtkInstantiatorvtkInterpolateDataSetAttributesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKdNode", vtkInstantiatorvtkKdNodeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKdTree", vtkInstantiatorvtkKdTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLineSource", vtkInstantiatorvtkLineSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLinearExtrusionFilter", vtkInstantiatorvtkLinearExtrusionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLinearSubdivisionFilter", vtkInstantiatorvtkLinearSubdivisionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLinkEdgels", vtkInstantiatorvtkLinkEdgelsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLoopSubdivisionFilter", vtkInstantiatorvtkLoopSubdivisionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMarchingContourFilter", vtkInstantiatorvtkMarchingContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMarchingCubes", vtkInstantiatorvtkMarchingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMarchingSquares", vtkInstantiatorvtkMarchingSquaresNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaskFields", vtkInstantiatorvtkMaskFieldsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaskPoints", vtkInstantiatorvtkMaskPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaskPolyData", vtkInstantiatorvtkMaskPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMassProperties", vtkInstantiatorvtkMassPropertiesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeDataObjectFilter", vtkInstantiatorvtkMergeDataObjectFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeCells", vtkInstantiatorvtkMergeCellsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeFields", vtkInstantiatorvtkMergeFieldsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeFilter", vtkInstantiatorvtkMergeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMeshQuality", vtkInstantiatorvtkMeshQualityNew);
  vtkInstantiator::UnRegisterInstantiator("vtkModelMetadata", vtkInstantiatorvtkModelMetadataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOBBDicer", vtkInstantiatorvtkOBBDicerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOBBTree", vtkInstantiatorvtkOBBTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineCornerFilter", vtkInstantiatorvtkOutlineCornerFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineCornerSource", vtkInstantiatorvtkOutlineCornerSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineFilter", vtkInstantiatorvtkOutlineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineSource", vtkInstantiatorvtkOutlineSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricFunctionSource", vtkInstantiatorvtkParametricFunctionSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlaneSource", vtkInstantiatorvtkPlaneSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlanesIntersection", vtkInstantiatorvtkPlanesIntersectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlatonicSolidSource", vtkInstantiatorvtkPlatonicSolidSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointDataToCellData", vtkInstantiatorvtkPointDataToCellDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointsProjectedHull", vtkInstantiatorvtkPointsProjectedHullNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointSource", vtkInstantiatorvtkPointSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataConnectivityFilter", vtkInstantiatorvtkPolyDataConnectivityFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataNormals", vtkInstantiatorvtkPolyDataNormalsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataStreamer", vtkInstantiatorvtkPolyDataStreamerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProbeFilter", vtkInstantiatorvtkProbeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableAttributeDataFilter", vtkInstantiatorvtkProgrammableAttributeDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableDataObjectSource", vtkInstantiatorvtkProgrammableDataObjectSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableFilter", vtkInstantiatorvtkProgrammableFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableGlyphFilter", vtkInstantiatorvtkProgrammableGlyphFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableSource", vtkInstantiatorvtkProgrammableSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProjectedTexture", vtkInstantiatorvtkProjectedTextureNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadricClustering", vtkInstantiatorvtkQuadricClusteringNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadricDecimation", vtkInstantiatorvtkQuadricDecimationNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuantizePolyDataPoints", vtkInstantiatorvtkQuantizePolyDataPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRearrangeFields", vtkInstantiatorvtkRearrangeFieldsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectangularButtonSource", vtkInstantiatorvtkRectangularButtonSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridClip", vtkInstantiatorvtkRectilinearGridClipNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridGeometryFilter", vtkInstantiatorvtkRectilinearGridGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridToTetrahedra", vtkInstantiatorvtkRectilinearGridToTetrahedraNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearSynchronizedTemplates", vtkInstantiatorvtkRectilinearSynchronizedTemplatesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRecursiveDividingCubes", vtkInstantiatorvtkRecursiveDividingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReflectionFilter", vtkInstantiatorvtkReflectionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRegularPolygonSource", vtkInstantiatorvtkRegularPolygonSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReverseSense", vtkInstantiatorvtkReverseSenseNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRibbonFilter", vtkInstantiatorvtkRibbonFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRotationalExtrusionFilter", vtkInstantiatorvtkRotationalExtrusionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRotationFilter", vtkInstantiatorvtkRotationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRuledSurfaceFilter", vtkInstantiatorvtkRuledSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelectPolyData", vtkInstantiatorvtkSelectPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShrinkFilter", vtkInstantiatorvtkShrinkFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShrinkPolyData", vtkInstantiatorvtkShrinkPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimpleElevationFilter", vtkInstantiatorvtkSimpleElevationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSliceCubes", vtkInstantiatorvtkSliceCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSmoothPolyDataFilter", vtkInstantiatorvtkSmoothPolyDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSortDataArray", vtkInstantiatorvtkSortDataArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpatialRepresentationFilter", vtkInstantiatorvtkSpatialRepresentationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpherePuzzle", vtkInstantiatorvtkSpherePuzzleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpherePuzzleArrows", vtkInstantiatorvtkSpherePuzzleArrowsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSphereSource", vtkInstantiatorvtkSphereSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSplineFilter", vtkInstantiatorvtkSplineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSplitField", vtkInstantiatorvtkSplitFieldNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamLine", vtkInstantiatorvtkStreamLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamPoints", vtkInstantiatorvtkStreamPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamTracer", vtkInstantiatorvtkStreamTracerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStripper", vtkInstantiatorvtkStripperNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridClip", vtkInstantiatorvtkStructuredGridClipNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridGeometryFilter", vtkInstantiatorvtkStructuredGridGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridOutlineFilter", vtkInstantiatorvtkStructuredGridOutlineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredPointsGeometryFilter", vtkInstantiatorvtkStructuredPointsGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSubPixelPositionEdgels", vtkInstantiatorvtkSubPixelPositionEdgelsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSubdivideTetra", vtkInstantiatorvtkSubdivideTetraNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSuperquadricSource", vtkInstantiatorvtkSuperquadricSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSynchronizedTemplates2D", vtkInstantiatorvtkSynchronizedTemplates2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSynchronizedTemplates3D", vtkInstantiatorvtkSynchronizedTemplates3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSynchronizedTemplatesCutter3D", vtkInstantiatorvtkSynchronizedTemplatesCutter3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTensorGlyph", vtkInstantiatorvtkTensorGlyphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextSource", vtkInstantiatorvtkTextSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextureMapToCylinder", vtkInstantiatorvtkTextureMapToCylinderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextureMapToPlane", vtkInstantiatorvtkTextureMapToPlaneNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextureMapToSphere", vtkInstantiatorvtkTextureMapToSphereNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTexturedSphereSource", vtkInstantiatorvtkTexturedSphereSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThreshold", vtkInstantiatorvtkThresholdNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThresholdPoints", vtkInstantiatorvtkThresholdPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThresholdTextureCoords", vtkInstantiatorvtkThresholdTextureCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformFilter", vtkInstantiatorvtkTransformFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformPolyDataFilter", vtkInstantiatorvtkTransformPolyDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformTextureCoords", vtkInstantiatorvtkTransformTextureCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangleFilter", vtkInstantiatorvtkTriangleFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangularTCoords", vtkInstantiatorvtkTriangularTCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTubeFilter", vtkInstantiatorvtkTubeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVectorDot", vtkInstantiatorvtkVectorDotNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVectorNorm", vtkInstantiatorvtkVectorNormNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVoxelContoursToSurfaceFilter", vtkInstantiatorvtkVoxelContoursToSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpLens", vtkInstantiatorvtkWarpLensNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpScalar", vtkInstantiatorvtkWarpScalarNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpTo", vtkInstantiatorvtkWarpToNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpVector", vtkInstantiatorvtkWarpVectorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWindowedSincPolyDataFilter", vtkInstantiatorvtkWindowedSincPolyDataFilterNew);

  
}

vtkGraphicsInstantiator::vtkGraphicsInstantiator()
{
  if(++vtkGraphicsInstantiator::Count == 1)
    { 
    vtkGraphicsInstantiator::ClassInitialize(); 
    }
}

vtkGraphicsInstantiator::~vtkGraphicsInstantiator()
{
  if(--vtkGraphicsInstantiator::Count == 0)
    { 
    vtkGraphicsInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkGraphicsInstantiator::Count;
