# Install script for directory: M:/thirdparties/VTK5.6/src/Graphics

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files/VTK")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")
  IF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.6" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/thirdparties/VTK5.6/src/bin/Debug/vtkGraphics.lib")
  ELSEIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.6" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/thirdparties/VTK5.6/src/bin/Release/vtkGraphics.lib")
  ELSEIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.6" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/thirdparties/VTK5.6/src/bin/MinSizeRel/vtkGraphics.lib")
  ELSEIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.6" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/thirdparties/VTK5.6/src/bin/RelWithDebInfo/vtkGraphics.lib")
  ENDIF()
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "RuntimeLibraries")
  IF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "M:/thirdparties/VTK5.6/src/bin/Debug/vtkGraphics.dll")
  ELSEIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "M:/thirdparties/VTK5.6/src/bin/Release/vtkGraphics.dll")
  ELSEIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "M:/thirdparties/VTK5.6/src/bin/MinSizeRel/vtkGraphics.dll")
  ELSEIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "M:/thirdparties/VTK5.6/src/bin/RelWithDebInfo/vtkGraphics.dll")
  ENDIF()
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "RuntimeLibraries")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/vtk-5.6" TYPE FILE FILES
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAnnotationLink.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAppendCompositeDataLeaves.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAppendFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAppendPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAppendSelection.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkApproximatingSubdivisionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkArcSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkArrayCalculator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkArrowSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAssignAttribute.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAttributeDataToFieldDataFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkAxes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkBandedPolyDataContourFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkBlankStructuredGrid.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkBlankStructuredGridWithImage.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkBlockIdScalars.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkBoxClipDataSet.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkBrownianPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkButterflySubdivisionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkButtonSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCellCenters.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCellDataToPointData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCellDerivatives.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCleanPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkClipDataSet.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkClipHyperOctree.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkClipPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkClipConvexPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkClipVolume.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCoincidentPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCompositeDataGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCompositeDataProbeFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkConeSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkConnectivityFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkContourFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkContourGrid.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkConvertSelection.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCubeSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCursor2D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCursor3D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCurvatures.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCutter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkCylinderSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDashedStreamLine.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataObjectGenerator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataObjectToDataSetFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataSetEdgeSubdivisionCriterion.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataSetGradient.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataSetGradientPrecompute.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataSetSurfaceFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataSetToDataObjectFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDataSetTriangleFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDecimatePolylineFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDecimatePro.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDelaunay2D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDelaunay3D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDensifyPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDicer.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDijkstraGraphGeodesicPath.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDijkstraImageGeodesicPath.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDiscreteMarchingCubes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkDiskSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkEdgePoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkEdgeSubdivisionCriterion.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkElevationFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkEllipticalButtonSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractArraysOverTime.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractBlock.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractCells.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractDataOverTime.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractDataSets.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractEdges.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractGeometry.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractGrid.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractLevel.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractPolyDataGeometry.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractRectilinearGrid.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedBlock.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedFrustum.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedIds.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedLocations.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedPolyDataIds.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedRows.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectedThresholds.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelectionBase.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractSelection.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractTemporalFieldData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractTensorComponents.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractUnstructuredGrid.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkExtractVectorComponents.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkFeatureEdges.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkFieldDataToAttributeDataFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkFillHolesFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkFrustumSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGeodesicPath.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGlyph2D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGlyph3D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGlyphSource2D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGradientFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGraphGeodesicPath.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGraphLayoutFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGraphToPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGraphToPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkGridSynchronizedTemplates3D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHedgeHog.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHierarchicalDataExtractDataSets.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHierarchicalDataExtractLevel.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHierarchicalDataLevelFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHierarchicalDataSetGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHull.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeClipCutPointsGrabber.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeContourFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeCutter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeDepth.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeDualGridContourFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeFractalSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeLimiter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeSampleFunction.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeSurfaceFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperOctreeToUniformGridFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkHyperStreamline.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkIconGlyphFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkIdFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkImageDataGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkImageMarchingCubes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkImplicitTextureCoords.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkInterpolateDataSetAttributes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkInterpolatingSubdivisionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkKdTreeSelector.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkLevelIdScalars.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkLinearExtrusionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkLinearSubdivisionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkLineSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkLinkEdgels.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkLoopSubdivisionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMarchingContourFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMarchingCubes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMarchingSquares.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMaskFields.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMaskPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMaskPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMassProperties.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMergeCells.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMergeDataObjectFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMergeFields.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMergeFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMeshQuality.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkModelMetadata.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMultiBlockDataGroupFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMultiBlockMergeFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkMultiThreshold.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkOBBDicer.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkOBBTree.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkOutlineCornerFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkOutlineCornerSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkOutlineFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkOutlineSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkParametricFunctionSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPlaneSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPlatonicSolidSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPointDataToCellData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPointSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPolyDataConnectivityFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPolyDataNormals.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPolyDataPointSampler.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkPolyDataStreamer.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProbeFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProbeSelectedLocations.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProgrammableAttributeDataFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProgrammableDataObjectSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProgrammableFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProgrammableGlyphFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProgrammableSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkProjectedTexture.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkQuadraturePointInterpolator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkQuadraturePointsGenerator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkQuadratureSchemeDictionaryGenerator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkQuadricClustering.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkQuadricDecimation.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkQuantizePolyDataPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRandomAttributeGenerator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRearrangeFields.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRectangularButtonSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRectilinearGridClip.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRectilinearGridGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRectilinearGridToTetrahedra.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRectilinearSynchronizedTemplates.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRecursiveDividingCubes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkReflectionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRegularPolygonSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkReverseSense.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRibbonFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRotationalExtrusionFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRotationFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkRuledSurfaceFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSectorSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSelectEnclosedPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSelectionSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSelectPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkShrinkFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkShrinkPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSimpleElevationFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSliceCubes.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSmoothPolyDataFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSpatialRepresentationFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSpherePuzzleArrows.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSpherePuzzle.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSphereSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSplineFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSplitField.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStreamer.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStreamingTessellator.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStreamLine.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStreamPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStreamTracer.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStripper.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStructuredGridClip.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStructuredGridGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStructuredGridOutlineFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkStructuredPointsGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSubdivideTetra.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSubPixelPositionEdgels.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSuperquadricSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSynchronizedTemplates2D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSynchronizedTemplates3D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkSynchronizedTemplatesCutter3D.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTableBasedClipDataSet.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTableToPolyData.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTableToStructuredGrid.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTemporalPathLineFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTemporalStatistics.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTensorGlyph.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTessellatorFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTessellatedBoxSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTextSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTexturedSphereSource.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTextureMapToCylinder.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTextureMapToPlane.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTextureMapToSphere.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkThreshold.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkThresholdPoints.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkThresholdTextureCoords.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTimeSourceExample.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTransformCoordinateSystems.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTransformFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTransformPolyDataFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTransformTextureCoords.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTriangleFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTriangularTCoords.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkTubeFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkUncertaintyTubeFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkUnstructuredGridGeometryFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkVectorDot.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkVectorNorm.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkVertexGlyphFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkVoxelContoursToSurfaceFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkWarpLens.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkWarpScalar.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkWarpTo.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkWarpVector.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkWindowedSincPolyDataFilter.h"
    "M:/thirdparties/VTK5.6/src/Graphics/vtkYoungsMaterialInterface.h"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.6" TYPE FILE FILES "M:/thirdparties/VTK5.6/src/Utilities/InstallOnly/vtkGraphicsKit.cmake")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")

