# CMake generated Testfile for 
# Source directory: M:/thirdparties/VTK5.6/src/Rendering/Testing/Cxx
# Build directory: M:/thirdparties/VTK5.6/src/Rendering/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(otherCoordinate "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "otherCoordinate" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestPriorityStreaming "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestPriorityStreaming" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(LoadOpenGLExtension "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "LoadOpenGLExtension" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestActorLightingFlag "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestActorLightingFlag" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestAnimationScene "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestAnimationScene" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestBlurAndSobelPasses "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestBlurAndSobelPasses" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestDynamic2DLabelMapper "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestDynamic2DLabelMapper" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestFBO "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestFBO" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestGaussianBlurPass "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestGaussianBlurPass" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestGPUInfo "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestGPUInfo" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestGradientBackground "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestGradientBackground" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestInteractorTimers "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestInteractorTimers" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLabelPlacer "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLabelPlacer" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLabelPlacer2D "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLabelPlacer2D" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLabelPlacerCoincidentPoints "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLabelPlacerCoincidentPoints" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLabelPlacementMapper2D "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLabelPlacementMapper2D" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLabelPlacementMapperCoincidentPoints "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLabelPlacementMapperCoincidentPoints" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLightActor "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLightActor" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestLODActor "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestLODActor" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestManyActors "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestManyActors" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestOrderedTriangulator "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestOrderedTriangulator" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestOpacity "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestOpacity" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestOSConeCxx "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestOSConeCxx" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestPOVExporter "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestPOVExporter" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestResetCameraVerticalAspectRatio "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestResetCameraVerticalAspectRatio" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestResetCameraVerticalAspectRatioParallel "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestResetCameraVerticalAspectRatioParallel" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestSobelGradientMagnitudePass "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestSobelGradientMagnitudePass" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestShadowMapPass "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestShadowMapPass" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTextActorAlphaBlending "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTextActorAlphaBlending" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTextActorDepthPeeling "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTextActorDepthPeeling" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTextActor3DAlphaBlending "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTextActor3DAlphaBlending" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTextActor3DDepthPeeling "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTextActor3DDepthPeeling" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTexturedBackground "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTexturedBackground" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTDx "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTDx" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTilingCxx "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTilingCxx" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTranslucentLUTAlphaBlending "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTranslucentLUTAlphaBlending" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTranslucentLUTDepthPeeling "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTranslucentLUTDepthPeeling" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTranslucentLUTDepthPeelingPass "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTranslucentLUTDepthPeelingPass" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTranslucentLUTTextureAlphaBlending "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTranslucentLUTTextureAlphaBlending" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestTranslucentLUTTextureDepthPeeling "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestTranslucentLUTTextureDepthPeeling" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLCxx "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLCxx" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLAlphaBlending "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLAlphaBlending" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLDepthPeelingPass "M:/thirdparties/VTK5.6/src/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLDepthPeelingPass" "-T" "M:/thirdparties/VTK5.6/src/Testing/Temporary")
SET_TESTS_PROPERTIES(TestGenericVertexAttributesGLSLDepthPeelingPass PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:.*vtkOpenGLProperty.*Couldn't build the shader program. At this point , it can be an error in a shader or a driver bug.")
