# CMake generated Testfile for 
# Source directory: M:/thirdparties/VTK5.6/src/Infovis/Testing/Cxx
# Build directory: M:/thirdparties/VTK5.6/src/Infovis/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(Infovis-TestArcEdges "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestArcEdges")
ADD_TEST(Infovis-TestAssignCoordinates "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestAssignCoordinates")
ADD_TEST(Infovis-TestCollapseVerticesByArray "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestCollapseVerticesByArray")
ADD_TEST(Infovis-TestContingencyStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestContingencyStatistics")
ADD_TEST(Infovis-TestCorrelativeStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestCorrelativeStatistics")
ADD_TEST(Infovis-TestCosmicTreeLayoutStrategy "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestCosmicTreeLayoutStrategy")
ADD_TEST(Infovis-TestDataObjectToTable "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestDataObjectToTable")
ADD_TEST(Infovis-TestDescriptiveStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestDescriptiveStatistics")
ADD_TEST(Infovis-TestExtractSelectedGraph "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestExtractSelectedGraph")
ADD_TEST(Infovis-TestGraph "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestGraph")
ADD_TEST(Infovis-TestGraphAttributes "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestGraphAttributes")
ADD_TEST(Infovis-TestGraphAlgorithms "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestGraphAlgorithms")
ADD_TEST(Infovis-TestGraphHierarchicalBundle "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestGraphHierarchicalBundle")
ADD_TEST(Infovis-TestGraphLayoutStrategy "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestGraphLayoutStrategy")
ADD_TEST(Infovis-TestGroupLeafVertices "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestGroupLeafVertices")
ADD_TEST(Infovis-TestKdTreeBoxSelection "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestKdTreeBoxSelection")
ADD_TEST(Infovis-TestKMeansStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestKMeansStatistics")
ADD_TEST(Infovis-TestMergeGraphs "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestMergeGraphs")
ADD_TEST(Infovis-TestMultiCorrelativeStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestMultiCorrelativeStatistics")
ADD_TEST(Infovis-TestOrderStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestOrderStatistics")
ADD_TEST(Infovis-TestPassArrays "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestPassArrays")
ADD_TEST(Infovis-TestPassThrough "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestPassThrough")
ADD_TEST(Infovis-TestPCAStatistics "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestPCAStatistics")
ADD_TEST(Infovis-TestPruneTreeFilter "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestPruneTreeFilter")
ADD_TEST(Infovis-TestRandomGraphSource "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestRandomGraphSource")
ADD_TEST(Infovis-TestSimple3DCirclesStrategy "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestSimple3DCirclesStrategy")
ADD_TEST(Infovis-TestStreamGraph "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestStreamGraph")
ADD_TEST(Infovis-TestStringToCategory "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestStringToCategory")
ADD_TEST(Infovis-TestTable "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestTable")
ADD_TEST(Infovis-TestTableSplitColumnComponents "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestTableSplitColumnComponents")
ADD_TEST(Infovis-TestTreeMapLayoutStrategy "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestTreeMapLayoutStrategy")
ADD_TEST(Infovis-TestThresholdTable "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestThresholdTable")
ADD_TEST(Infovis-TestVariantArray "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestVariantArray")
ADD_TEST(Infovis-TestVariant "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestVariant")
ADD_TEST(Infovis-TestSQLGraphReader "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestSQLGraphReader")
ADD_TEST(Infovis-TestTimePoint "M:/thirdparties/VTK5.6/src/bin/InfovisCxxTests" "TestTimePoint")
ADD_TEST(Array-ArrayAPIDenseCoordinates "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayAPIDenseCoordinates")
ADD_TEST(Array-ArrayDiagonalMatrixSource "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayDiagonalMatrixSource")
ADD_TEST(Array-ArrayDotProductSimilarity "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayDotProductSimilarity")
ADD_TEST(Array-ArrayExtractFactoredArray "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayExtractFactoredArray")
ADD_TEST(Array-ArrayMatricizeArray "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayMatricizeArray")
ADD_TEST(Array-TestArrayNorm "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "TestArrayNorm")
ADD_TEST(Array-ArrayNormalizeMatrixVectors "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayNormalizeMatrixVectors")
ADD_TEST(Array-ArraySparseArrayToTable "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArraySparseArrayToTable")
ADD_TEST(Array-ArrayTableToSparseArray "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayTableToSparseArray")
ADD_TEST(Array-ArrayToTable "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayToTable")
ADD_TEST(Array-ArrayTransposeMatrix "M:/thirdparties/VTK5.6/src/bin/InfovisArrayCxxTests" "ArrayTransposeMatrix")
