//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeSimulation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipeSimulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackView {
            get {
                object obj = ResourceManager.GetObject("BackView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BeginingAnimation {
            get {
                object obj = ResourceManager.GetObject("BeginingAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomView {
            get {
                object obj = ResourceManager.GetObject("BottomView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connectionpairs {
            get {
                object obj = ResourceManager.GetObject("connectionpairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EndAnimation {
            get {
                object obj = ResourceManager.GetObject("EndAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrontView {
            get {
                object obj = ResourceManager.GetObject("FrontView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于 {0} {0}.
        /// </summary>
        internal static string IDS_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("IDS_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本 {0} {0}.
        /// </summary>
        internal static string IDS_ABOUT_VERSION {
            get {
                return ResourceManager.GetString("IDS_ABOUT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倾角在正常范围内。.
        /// </summary>
        internal static string IDS_ANGLE_NO_WARNING {
            get {
                return ResourceManager.GetString("IDS_ANGLE_NO_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 俯仰角为{0}度，超过预设值{1}。.
        /// </summary>
        internal static string IDS_ANGLE_PITCH_WARNING {
            get {
                return ResourceManager.GetString("IDS_ANGLE_PITCH_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧滚角为{0}度，超过预设值{1}。.
        /// </summary>
        internal static string IDS_ANGLE_ROLL_WARNING {
            get {
                return ResourceManager.GetString("IDS_ANGLE_ROLL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVI 文件|*.avi.
        /// </summary>
        internal static string IDS_AVI_FILTER {
            get {
                return ResourceManager.GetString("IDS_AVI_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库已经成功连接。.
        /// </summary>
        internal static string IDS_DB_CONNECTED {
            get {
                return ResourceManager.GetString("IDS_DB_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未连接到数据库。.
        /// </summary>
        internal static string IDS_DB_DIS_CONNECTED {
            get {
                return ResourceManager.GetString("IDS_DB_DIS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能连接到数据库。.
        /// </summary>
        internal static string IDS_ERROR_DATAENGINE_CONNECT {
            get {
                return ResourceManager.GetString("IDS_ERROR_DATAENGINE_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 致命错误：不能找到{0}。.
        /// </summary>
        internal static string IDS_ERROR_DATAFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_ERROR_DATAFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误：读取某些模型文件出错。.
        /// </summary>
        internal static string IDS_ERROR_LOAD_MODEL {
            get {
                return ResourceManager.GetString("IDS_ERROR_LOAD_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 致命错误：读取{0}出错。.
        /// </summary>
        internal static string IDS_ERROR_LOAD_XML {
            get {
                return ResourceManager.GetString("IDS_ERROR_LOAD_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大倾角必须大于0.
        /// </summary>
        internal static string IDS_ERROR_MAXIMUMANGLE {
            get {
                return ResourceManager.GetString("IDS_ERROR_MAXIMUMANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本文档|*.txt.
        /// </summary>
        internal static string IDS_EXPORT_PIPE_INFO_FILETER {
            get {
                return ResourceManager.GetString("IDS_EXPORT_PIPE_INFO_FILETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出当前浮运沉放信息.
        /// </summary>
        internal static string IDS_EXPORT_PIPE_INFO_TITLE {
            get {
                return ResourceManager.GetString("IDS_EXPORT_PIPE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请联系开发者关于以下信息:.
        /// </summary>
        internal static string IDS_FATAL_ERROR_TEXT {
            get {
                return ResourceManager.GetString("IDS_FATAL_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 致命错误.
        /// </summary>
        internal static string IDS_FATAL_ERROR_TITLE {
            get {
                return ResourceManager.GetString("IDS_FATAL_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回填模拟.
        /// </summary>
        internal static string IDS_FILL_SIM_DLG_TITLE {
            get {
                return ResourceManager.GetString("IDS_FILL_SIM_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入模型....
        /// </summary>
        internal static string IDS_IMPORT_MODELS {
            get {
                return ResourceManager.GetString("IDS_IMPORT_MODELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实时监听模式.
        /// </summary>
        internal static string IDS_MONITOR_MODE_TEXT {
            get {
                return ResourceManager.GetString("IDS_MONITOR_MODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到该时刻的数据.
        /// </summary>
        internal static string IDS_NODATA_TO_TIME {
            get {
                return ResourceManager.GetString("IDS_NODATA_TO_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平移视图.
        /// </summary>
        internal static string IDS_PAN_DESC {
            get {
                return ResourceManager.GetString("IDS_PAN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}段沉管.
        /// </summary>
        internal static string IDS_PIPE_FILL_INDEX {
            get {
                return ResourceManager.GetString("IDS_PIPE_FILL_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}段沉管正在浮运沉放.
        /// </summary>
        internal static string IDS_PIPE_ID_IMMSERING {
            get {
                return ResourceManager.GetString("IDS_PIPE_ID_IMMSERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看第{0}段沉管沉放过程.
        /// </summary>
        internal static string IDS_PIPE_INDEX {
            get {
                return ResourceManager.GetString("IDS_PIPE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧滚角: {0} 最大侧滚角: {1} 俯仰角: {2} 最大俯仰角: {3}.
        /// </summary>
        internal static string IDS_PIPE_INFO_ANGLE {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}个对接点：距离{1}, X分量{2}, Y分量{3}, Z分量{4}.
        /// </summary>
        internal static string IDS_PIPE_INFO_CONNECTION_PAIR {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_CONNECTION_PAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮运沉放时间: {0}.
        /// </summary>
        internal static string IDS_PIPE_INFO_DATE_TIME {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_DATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1个GPS坐标信息: {0}.
        /// </summary>
        internal static string IDS_PIPE_INFO_GPS1 {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_GPS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2个GPS坐标信息: {0}.
        /// </summary>
        internal static string IDS_PIPE_INFO_GPS2 {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_GPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看所有沉管浮运沉放过程.
        /// </summary>
        internal static string IDS_PIPES_ALL {
            get {
                return ResourceManager.GetString("IDS_PIPES_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG 文件|*.png.
        /// </summary>
        internal static string IDS_PNG_FILTER {
            get {
                return ResourceManager.GetString("IDS_PNG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放模式.
        /// </summary>
        internal static string IDS_REPLAY_MODE_TEXT {
            get {
                return ResourceManager.GetString("IDS_REPLAY_MODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转视图.
        /// </summary>
        internal static string IDS_ROTATE_DESC {
            get {
                return ResourceManager.GetString("IDS_ROTATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截取当前屏幕.
        /// </summary>
        internal static string IDS_SAVE_PICTURE_TITLE {
            get {
                return ResourceManager.GetString("IDS_SAVE_PICTURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动程序....
        /// </summary>
        internal static string IDS_START_APP {
            get {
                return ResourceManager.GetString("IDS_START_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监测中.
        /// </summary>
        internal static string IDS_STATUS_MONITOR {
            get {
                return ResourceManager.GetString("IDS_STATUS_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现在运行的是【{0}】。.
        /// </summary>
        internal static string IDS_STATUS_OBSERVER_MODE {
            get {
                return ResourceManager.GetString("IDS_STATUS_OBSERVER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 准备就绪.
        /// </summary>
        internal static string IDS_STATUS_READY {
            get {
                return ResourceManager.GetString("IDS_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在回放.
        /// </summary>
        internal static string IDS_STATUS_REPLAY {
            get {
                return ResourceManager.GetString("IDS_STATUS_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能打开{0}。.
        /// </summary>
        internal static string IDS_VIDEO_OPENFILE_FAIL {
            get {
                return ResourceManager.GetString("IDS_VIDEO_OPENFILE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频文件{0}已经录制成功。您想打开该视频吗？.
        /// </summary>
        internal static string IDS_VIDEO_OUTPUT_SUCCEED {
            get {
                return ResourceManager.GetString("IDS_VIDEO_OUTPUT_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存视频文件.
        /// </summary>
        internal static string IDS_VIDEO_TITLE {
            get {
                return ResourceManager.GetString("IDS_VIDEO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您真的想退出程序？.
        /// </summary>
        internal static string IDS_WARNING_EXIT {
            get {
                return ResourceManager.GetString("IDS_WARNING_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在录制视频，关闭程序前请先停止录制！.
        /// </summary>
        internal static string IDS_WARNING_ISRECORDING {
            get {
                return ResourceManager.GetString("IDS_WARNING_ISRECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置已修改，是否保存？.
        /// </summary>
        internal static string IDS_WARNING_SAVE_CONFIG {
            get {
                return ResourceManager.GetString("IDS_WARNING_SAVE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注浆模拟.
        /// </summary>
        internal static string IDS_ZHUJIANG_SIM_DLG_TITLE {
            get {
                return ResourceManager.GetString("IDS_ZHUJIANG_SIM_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放视图.
        /// </summary>
        internal static string IDS_ZOOM_DESC {
            get {
                return ResourceManager.GetString("IDS_ZOOM_DESC", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LeftView {
            get {
                object obj = ResourceManager.GetObject("LeftView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarOrbit {
            get {
                object obj = ResourceManager.GetObject("NavBarOrbit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarPan {
            get {
                object obj = ResourceManager.GetObject("NavBarPan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarZoom {
            get {
                object obj = ResourceManager.GetObject("NavBarZoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarZoomAll {
            get {
                object obj = ResourceManager.GetObject("NavBarZoomAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NEIsoMetric {
            get {
                object obj = ResourceManager.GetObject("NEIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NWIsoMetric {
            get {
                object obj = ResourceManager.GetObject("NWIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseAnimation {
            get {
                object obj = ResourceManager.GetObject("PauseAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap record_icon {
            get {
                object obj = ResourceManager.GetObject("record_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightView {
            get {
                object obj = ResourceManager.GetObject("RightView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SEIsoMetric {
            get {
                object obj = ResourceManager.GetObject("SEIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartAnimation {
            get {
                object obj = ResourceManager.GetObject("StartAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopAnimation {
            get {
                object obj = ResourceManager.GetObject("StopAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWIsoMetric {
            get {
                object obj = ResourceManager.GetObject("SWIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SWOrbit {
            get {
                object obj = ResourceManager.GetObject("SWOrbit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SWPan {
            get {
                object obj = ResourceManager.GetObject("SWPan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SWZoom {
            get {
                object obj = ResourceManager.GetObject("SWZoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopView {
            get {
                object obj = ResourceManager.GetObject("TopView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
