//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeSimulation.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipeSimulation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackView {
            get {
                object obj = ResourceManager.GetObject("BackView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BeginingAnimation {
            get {
                object obj = ResourceManager.GetObject("BeginingAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomView {
            get {
                object obj = ResourceManager.GetObject("BottomView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EndAnimation {
            get {
                object obj = ResourceManager.GetObject("EndAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrontView {
            get {
                object obj = ResourceManager.GetObject("FrontView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关于 {0} {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("IDS_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_ABOUT_VERSION {
            get {
                return ResourceManager.GetString("IDS_ABOUT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倾角在正常范围内。 的本地化字符串。
        /// </summary>
        internal static string IDS_ANGLE_NO_WARNING {
            get {
                return ResourceManager.GetString("IDS_ANGLE_NO_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俯仰角为{0}度，超过预设值{1}。 的本地化字符串。
        /// </summary>
        internal static string IDS_ANGLE_PITCH_WARNING {
            get {
                return ResourceManager.GetString("IDS_ANGLE_PITCH_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 侧滚角为{0}度，超过预设值{1}。 的本地化字符串。
        /// </summary>
        internal static string IDS_ANGLE_ROLL_WARNING {
            get {
                return ResourceManager.GetString("IDS_ANGLE_ROLL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AVI 文件|*.avi 的本地化字符串。
        /// </summary>
        internal static string IDS_AVI_FILTER {
            get {
                return ResourceManager.GetString("IDS_AVI_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库已经成功连接。 的本地化字符串。
        /// </summary>
        internal static string IDS_DB_CONNECTED {
            get {
                return ResourceManager.GetString("IDS_DB_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接到数据库。 的本地化字符串。
        /// </summary>
        internal static string IDS_DB_DIS_CONNECTED {
            get {
                return ResourceManager.GetString("IDS_DB_DIS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能连接到数据库。 的本地化字符串。
        /// </summary>
        internal static string IDS_ERROR_DATAENGINE_CONNECT {
            get {
                return ResourceManager.GetString("IDS_ERROR_DATAENGINE_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致命错误：不能找到{0}。 的本地化字符串。
        /// </summary>
        internal static string IDS_ERROR_DATAFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_ERROR_DATAFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：读取某些模型文件出错。 的本地化字符串。
        /// </summary>
        internal static string IDS_ERROR_LOAD_MODEL {
            get {
                return ResourceManager.GetString("IDS_ERROR_LOAD_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致命错误：读取{0}出错。 的本地化字符串。
        /// </summary>
        internal static string IDS_ERROR_LOAD_XML {
            get {
                return ResourceManager.GetString("IDS_ERROR_LOAD_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大倾角必须大于0 的本地化字符串。
        /// </summary>
        internal static string IDS_ERROR_MAXIMUMANGLE {
            get {
                return ResourceManager.GetString("IDS_ERROR_MAXIMUMANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文档|*.txt 的本地化字符串。
        /// </summary>
        internal static string IDS_EXPORT_PIPE_INFO_FILETER {
            get {
                return ResourceManager.GetString("IDS_EXPORT_PIPE_INFO_FILETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出当前沉放信息 的本地化字符串。
        /// </summary>
        internal static string IDS_EXPORT_PIPE_INFO_TITLE {
            get {
                return ResourceManager.GetString("IDS_EXPORT_PIPE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系开发者关于以下信息: 的本地化字符串。
        /// </summary>
        internal static string IDS_FATAL_ERROR_TEXT {
            get {
                return ResourceManager.GetString("IDS_FATAL_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致命错误 的本地化字符串。
        /// </summary>
        internal static string IDS_FATAL_ERROR_TITLE {
            get {
                return ResourceManager.GetString("IDS_FATAL_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回填模拟 的本地化字符串。
        /// </summary>
        internal static string IDS_FILL_SIM_DLG_TITLE {
            get {
                return ResourceManager.GetString("IDS_FILL_SIM_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入模型... 的本地化字符串。
        /// </summary>
        internal static string IDS_IMPORT_MODELS {
            get {
                return ResourceManager.GetString("IDS_IMPORT_MODELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [实时监听模式] 的本地化字符串。
        /// </summary>
        internal static string IDS_MONITOR_MODE_TEXT {
            get {
                return ResourceManager.GetString("IDS_MONITOR_MODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到该时刻的数据 的本地化字符串。
        /// </summary>
        internal static string IDS_NODATA_TO_TIME {
            get {
                return ResourceManager.GetString("IDS_NODATA_TO_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平移视图 的本地化字符串。
        /// </summary>
        internal static string IDS_PAN_DESC {
            get {
                return ResourceManager.GetString("IDS_PAN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}段沉管 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_FILL_INDEX {
            get {
                return ResourceManager.GetString("IDS_PIPE_FILL_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}段沉管正在沉放 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_ID_IMMSERING {
            get {
                return ResourceManager.GetString("IDS_PIPE_ID_IMMSERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看第{0}段沉管沉放过程 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_INDEX {
            get {
                return ResourceManager.GetString("IDS_PIPE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 侧滚角: {0} 最大侧滚角: {1} 俯仰角: {2} 最大俯仰角: {3} 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_INFO_ANGLE {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}个对接点：距离{1}, X分量{2}, Y分量{3}, Z分量{4} 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_INFO_CONNECTION_PAIR {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_CONNECTION_PAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沉放时间: {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_INFO_DATE_TIME {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_DATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第1个GPS坐标信息: {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_INFO_GPS1 {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_GPS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第2个GPS坐标信息: {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPE_INFO_GPS2 {
            get {
                return ResourceManager.GetString("IDS_PIPE_INFO_GPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有沉管沉放过程 的本地化字符串。
        /// </summary>
        internal static string IDS_PIPES_ALL {
            get {
                return ResourceManager.GetString("IDS_PIPES_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG 文件|*.png 的本地化字符串。
        /// </summary>
        internal static string IDS_PNG_FILTER {
            get {
                return ResourceManager.GetString("IDS_PNG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [回放模式] 的本地化字符串。
        /// </summary>
        internal static string IDS_REPLAY_MODE_TEXT {
            get {
                return ResourceManager.GetString("IDS_REPLAY_MODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转视图 的本地化字符串。
        /// </summary>
        internal static string IDS_ROTATE_DESC {
            get {
                return ResourceManager.GetString("IDS_ROTATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截取当前屏幕 的本地化字符串。
        /// </summary>
        internal static string IDS_SAVE_PICTURE_TITLE {
            get {
                return ResourceManager.GetString("IDS_SAVE_PICTURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动程序... 的本地化字符串。
        /// </summary>
        internal static string IDS_START_APP {
            get {
                return ResourceManager.GetString("IDS_START_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监测中 的本地化字符串。
        /// </summary>
        internal static string IDS_STATUS_MONITOR {
            get {
                return ResourceManager.GetString("IDS_STATUS_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在运行的是【{0}】。 的本地化字符串。
        /// </summary>
        internal static string IDS_STATUS_OBSERVER_MODE {
            get {
                return ResourceManager.GetString("IDS_STATUS_OBSERVER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        internal static string IDS_STATUS_READY {
            get {
                return ResourceManager.GetString("IDS_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在回放 的本地化字符串。
        /// </summary>
        internal static string IDS_STATUS_REPLAY {
            get {
                return ResourceManager.GetString("IDS_STATUS_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能打开{0}。 的本地化字符串。
        /// </summary>
        internal static string IDS_VIDEO_OPENFILE_FAIL {
            get {
                return ResourceManager.GetString("IDS_VIDEO_OPENFILE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频文件{0}已经录制成功。您想打开该视频吗？ 的本地化字符串。
        /// </summary>
        internal static string IDS_VIDEO_OUTPUT_SUCCEED {
            get {
                return ResourceManager.GetString("IDS_VIDEO_OUTPUT_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存视频文件 的本地化字符串。
        /// </summary>
        internal static string IDS_VIDEO_TITLE {
            get {
                return ResourceManager.GetString("IDS_VIDEO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您真的想退出程序？ 的本地化字符串。
        /// </summary>
        internal static string IDS_WARNING_EXIT {
            get {
                return ResourceManager.GetString("IDS_WARNING_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在录制视频，关闭程序前请先停止录制！ 的本地化字符串。
        /// </summary>
        internal static string IDS_WARNING_ISRECORDING {
            get {
                return ResourceManager.GetString("IDS_WARNING_ISRECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置已修改，是否保存？ 的本地化字符串。
        /// </summary>
        internal static string IDS_WARNING_SAVE_CONFIG {
            get {
                return ResourceManager.GetString("IDS_WARNING_SAVE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注浆模拟 的本地化字符串。
        /// </summary>
        internal static string IDS_ZHUJIANG_SIM_DLG_TITLE {
            get {
                return ResourceManager.GetString("IDS_ZHUJIANG_SIM_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放视图 的本地化字符串。
        /// </summary>
        internal static string IDS_ZOOM_DESC {
            get {
                return ResourceManager.GetString("IDS_ZOOM_DESC", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LeftView {
            get {
                object obj = ResourceManager.GetObject("LeftView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarOrbit {
            get {
                object obj = ResourceManager.GetObject("NavBarOrbit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarPan {
            get {
                object obj = ResourceManager.GetObject("NavBarPan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarZoom {
            get {
                object obj = ResourceManager.GetObject("NavBarZoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBarZoomAll {
            get {
                object obj = ResourceManager.GetObject("NavBarZoomAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NEIsoMetric {
            get {
                object obj = ResourceManager.GetObject("NEIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NWIsoMetric {
            get {
                object obj = ResourceManager.GetObject("NWIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseAnimation {
            get {
                object obj = ResourceManager.GetObject("PauseAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap record_icon {
            get {
                object obj = ResourceManager.GetObject("record_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightView {
            get {
                object obj = ResourceManager.GetObject("RightView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SEIsoMetric {
            get {
                object obj = ResourceManager.GetObject("SEIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartAnimation {
            get {
                object obj = ResourceManager.GetObject("StartAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopAnimation {
            get {
                object obj = ResourceManager.GetObject("StopAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SWIsoMetric {
            get {
                object obj = ResourceManager.GetObject("SWIsoMetric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SWOrbit {
            get {
                object obj = ResourceManager.GetObject("SWOrbit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SWPan {
            get {
                object obj = ResourceManager.GetObject("SWPan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SWZoom {
            get {
                object obj = ResourceManager.GetObject("SWZoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopView {
            get {
                object obj = ResourceManager.GetObject("TopView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
