# CMake generated Testfile for 
# Source directory: M:/thirdparties/VTK5.6/src/Common/Testing/Cxx
# Build directory: M:/thirdparties/VTK5.6/src/Common/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(ObjectFactory "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "ObjectFactory")
ADD_TEST(otherArrays "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "otherArrays")
ADD_TEST(otherTimerLog "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "otherTimerLog")
ADD_TEST(otherLookupTable "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "otherLookupTable")
ADD_TEST(otherLookupTableWithEnabling "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "otherLookupTableWithEnabling")
ADD_TEST(otherByteSwap "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "otherByteSwap")
ADD_TEST(otherStringArray "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "otherStringArray")
ADD_TEST(TestAmoebaMinimizer "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestAmoebaMinimizer")
ADD_TEST(TestArrayLookup "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestArrayLookup")
ADD_TEST(TestConditionVariable "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestConditionVariable")
SET_TESTS_PROPERTIES(TestConditionVariable PROPERTIES  RUN_SERIAL "ON")
ADD_TEST(TestGarbageCollector "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestGarbageCollector")
ADD_TEST(TestDataArray "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestDataArray")
ADD_TEST(TestDirectory "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestDirectory")
ADD_TEST(TestFastNumericConversion "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestFastNumericConversion")
ADD_TEST(TestMath "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestMath")
ADD_TEST(TestMatrix3x3 "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestMatrix3x3")
ADD_TEST(TestMinimalStandardRandomSequence "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestMinimalStandardRandomSequence")
ADD_TEST(TestPolynomialSolversUnivariate "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestPolynomialSolversUnivariate")
ADD_TEST(TestSmartPointer "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestSmartPointer")
ADD_TEST(TestSortDataArray "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestSortDataArray")
ADD_TEST(TestUnicodeStringAPI "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestUnicodeStringAPI")
ADD_TEST(TestUnicodeStringArrayAPI "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestUnicodeStringArrayAPI")
ADD_TEST(TestVariantComparison "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "TestVariantComparison")
ADD_TEST(SystemInformation "M:/thirdparties/VTK5.6/src/bin/CommonCxxTests" "SystemInformation")
ADD_TEST(TestCxxFeatures "M:/thirdparties/VTK5.6/src/bin/TestCxxFeatures")
ADD_TEST(TestInstantiator "M:/thirdparties/VTK5.6/src/bin/TestInstantiator")
ADD_TEST(Array-ArrayAPI "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayAPI")
ADD_TEST(Array-ArrayAPIConvenience "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayAPIConvenience")
ADD_TEST(Array-ArrayAPIDense "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayAPIDense")
ADD_TEST(Array-ArrayAPISparse "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayAPISparse")
ADD_TEST(Array-ArrayBool "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayBool")
ADD_TEST(Array-ArrayInterpolationDense "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayInterpolationDense")
ADD_TEST(Array-ArrayNullValues "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayNullValues")
ADD_TEST(Array-ArrayExtents "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayExtents")
ADD_TEST(Array-ArrayUserTypes "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayUserTypes")
ADD_TEST(Array-ArrayVariants "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "ArrayVariants")
ADD_TEST(Array-SparseArrayValidation "M:/thirdparties/VTK5.6/src/bin/ArrayCxxTests" "SparseArrayValidation")
