// Loadable modules
//
// Generated by ..\bin\Release\vtkVREncodeString.exe
//
#ifndef __vtkKWCommonProvtkVolumeTextureMapper3D_OneComponentNoShadeFP_h
#define __vtkKWCommonProvtkVolumeTextureMapper3D_OneComponentNoShadeFP_h

// Define the vtkVolumeTextureMapper3D_OneComponentNoShadeFP interfaces.
//
// Generated from file: M:/thirdparties/VTK.Net/src/VolumeRendering/vtkVolumeTextureMapper3D_OneComponentNoShadeFP.asm
//
const char* vtkVolumeTextureMapper3D_OneComponentNoShadeFP =
"!!ARBfp1.0\n"
"	\n"
"# This is the fragment program for one\n"
"# component data with no shading	\n"
"\n"
"# We need some temporary variables		\n"
"TEMP temp1, temp2, temp3;\n"
"\n"
"# We are going to use the first \n"
"# texture coordinate		\n"
"ATTRIB tex0 = fragment.texcoord[0];\n"
"	\n"
"# This is our output color\n"
"OUTPUT out = result.color;\n"
"\n"
"# Look up the scalar value / gradient\n"
"# magnitude in the first volume	\n"
"TEX temp1, tex0, texture[0], 3D;\n"
"\n"
"# Swizzle this to use (a,r) as texture\n"
"# coordinates	\n"
"SWZ temp2, temp1, a, r, 1, 1;\n"
"\n"
"# Use this coordinate to look up a \n"
"# final color in the second texture\n"
"# (this is a 2D texture)			\n"
"TEX temp3, temp2, texture[1], 2D;\n"
"\n"
"# That's our result and we are done\n"
"MOV out, temp3;\n"
"END\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"	\n";

#endif
